---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-storage-path
allowVolumeExpansion: true
mountOptions:
- noatime
- hard
- rsize=1048576
- wsize=1048576
- timeo=600
- retrans=2
- _netdev
- nofail
parameters:
  archiveOnDelete: "false"
  pathPattern: "${.PVC.annotations.nfs-storage-path}"
provisioner: nfs
reclaimPolicy: Retain # (-> Note: reclaimPolicy Delete is dangerous usage if storage-path is shared multiple pvc)
volumeBindingMode: Immediate