---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler
  namespace: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler
      containers:
      - name: autoscaler-container
        image: ghcr.io/castrogne/k8s_vagrant:latest
        imagePullPolicy: Always

