apiVersion: v1
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjoKICAgIHsKICAgICAgICAiZ2hjci5pbyI6CiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJhdXRoIjoiWTJGemRISnZaMjVsT21kb2NGOU9NV0ZOWVdFelVscFVObTlSYjBkRllrZFhaSFZIYUdSdldrbHVRelV3T0dOaWJYYz0iCiAgICAgICAgICAgIH0KICAgIH0KfQ==
kind: Secret
metadata:
  name: github-registry-credentials
  namespace: autoscaler
type: kubernetes.io/dockerconfigjson