
# HELM CHART
##  https://github.com/prometheus-community/helm-charts/tree/kube-prometheus-stack-54.2.2/charts/kube-prometheus-stack

#helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#helm repo update
## helm diff -n kube-monitoring upgrade --install prometheus prometheus-community/kube-prometheus-stack -f helm/kube-monitoring/kube-prometheus-stack.yml --version 55.5.1
## helm -n kube-monitoring upgrade --install prometheus prometheus-community/kube-prometheus-stack -f helm/kube-monitoring/kube-prometheus-stack.yml --version 55.5.1

# Install Operator CDR
crds:
  enabled: true

# Install Prometheus (via operator)
prometheus:
  enabled: true
 
  prometheusSpec:
    replicas: 1

    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            prometheus: prometheus-kube-prometheus-prometheus

    resources:
      requests:
        memory: 1Gi
      limits:
        memory: 1Gi

    # Allow operator object listen label on all namespace
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false

    # ensure slow ephemere disk usage
    retention: 30m
    retentionSize: "500MiB"

  # disable unused rules
  defaultRules:
    create: false

nodeExporter:
  enabled: true
  priorityClassName: system-node-critical

alertmanager:
  enabled: false

grafana:
  persistence:
    enabled: false
  replicas: 1
  useStatefulSet: true
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: prometheus
          app.kubernetes.io/name: grafana
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    limits:
      memory: 512Mi
  grafana.ini:
    auth:
      disable_login_form: true
    notifiers:  
      provisioning: true 
    auth.proxy:
      enabled: true
      header_name: X-WEBAUTH-USER
      header_property: username
      headers: Name:X-WEBAUTH-NAME Role:X-WEBAUTH-ROLE Email:X-WEBAUTH-EMAIL Groups:X-WEBAUTH-GROUPS
      auto_sign_up: true
    users:
      viewers_can_edit: true #  all "Viewer" as Editor role without save option (access to explorer)
      default_theme: system
      default_language: fr-FR
    dashboards:
      min_refresh_interval: 30s # override refresh community dashboards (no flood)
  sidecar:
    dashboards: 
      label: grafana_dashboard 
      folderAnnotation: grafana_folder 
      provider: 
        foldersFromFilesStructure: true 
    datasources:
      enabled: false  # no use prometheus datasource > use custom > thanos
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          uid: prometheus
          access: proxy
          type: prometheus
          url: http://prometheus-kube-prometheus-prometheus.kube-monitoring.svc.cluster.local:9090
          isDefault: true
          editable: false
          jsonData:
            tlsSkipVerify: true
            httpMethod: POST
            timeInterval: "30s"
          orgId: 1

  extraConfigmapMounts: 